site_name: classifier-uncertainty
theme:
  name: material
hooks:
  - hooks.py
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: numpy
            show_root_heading: true
            show_source: false
nav:
  - Home: index.md
  - Examples: examples.md
  - API Reference: api.md
